name: Acceptance Tests

on:
  push:
    branches: ["feature/unit-tests"]

jobs:
  acceptance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install
        working-directory: server-main

      - name: Correr testes de aceitação
        run: node --experimental-vm-modules node_modules/.bin/jest --runInBand --testPathPatterns="tests/acceptance"
        working-directory: server-main
