name: Lint Code Base

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  run-linter:
    name: Super-Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: feature/unit-tests
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_ES: true
